### ISSUE TITLE
missing gain config function for use with indi-allsky

### ISSUE THREAD

**Issue by gmke** [scriptorron/indi_pylibcamera#13]
Mar 10 13:07:38 astroberry [ERROR] MainProcess allsky.unhandled_exception() #41: '  File "/home/pi/indi-allsky/indi_allsky/camera/indi.py", line 990, in getCcdGain\n    raise Exception(\'Gain config not implemented for {0:s}, open an enhancement request\'.format(indi_exec))\n'
Mar 10 13:07:38 astroberry [ERROR] MainProcess allsky.unhandled_exception() #41: '  File "/home/pi/indi-allsky/indi_allsky/camera/indi.py", line 548, in getCcdInfo\n    gain_info = self.getCcdGain()\n'
Mar 10 13:07:38 astroberry [ERROR] MainProcess allsky.unhandled_exception() #41: '  File "/home/pi/indi-allsky/indi_allsky/allsky.py", line 536, in _initialize\n    ccd_info = self.indiclient.getCcdInfo()\n'
Mar 10 13:07:38 astroberry [ERROR] MainProcess allsky.unhandled_exception() #41: '  File "/home/pi/indi-allsky/indi_allsky/allsky.py", line 884, in run\n    self._initialize()\n'
Mar 10 13:07:38 astroberry [ERROR] MainProcess allsky.unhandled_exception() #41: '  File "/home/pi/indi-allsky/allsky.py", line 119, in <module>\n    action_func(*args_list, **kwargs_dict)\n'
Mar 10 13:07:38 astroberry [ERROR] MainProcess allsky.unhandled_exception() #36: Value: Gain config not implemented for ././indi_pylibcamera.py, open an enhancement request

**Comment by gmke** [comment]
Thank you so much for your kind analysis. I will report it to Aaron. I use the main branch of indi-allsky and had to manually start the indiserver to convince indi-allsky to use the puli camera.

CS, Markus
Am 10. März 2023, 16:30 +0100 schrieb scriptorron ***@***.***>:

**Comment by scriptorron** [comment]
Aaron, thank you very much. If all agree I would like to close this issue.
