### ISSUE TITLE
Setting to run in background?

### ISSUE THREAD

**Issue by wjschmitt** [scriptorron/indi_pylibcamera#71]
I'm running the indiserver on a RPi4b in a virtual env and it runs fine until I close the terminal session where I started it.  Then it stops.  Is there a setting to run in the background?  Thanks.

**Comment by scriptorron** [comment]
There are many option. You can also use the `screen` command which allows to get the terminal back after a disconnect. For an automated start after boot you can create a cron job with `crontab -e`  and add a line:
```
@reboot sleep 30 && $HOME/bin/YourScript.sh &
```
This will start YourScript 30 seconds after reboot. The delay allows to fully start the Pi. I am not sure if the `&` is needed at the end of the line.

**Comment by scriptorron** [comment]
Solved
